networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://duplexroot:b26032e8527d4991@db:5432/calendarDB
    depends_on:
      - db
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: duplexroot
      POSTGRES_PASSWORD: b26032e8527d4991
      POSTGRES_DB: calendarDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  postgres_data:
